namespace SeniorProjectMVC.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class Rebuild : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.XREF_AddressBookCustomer", "AddresBook_ID", "dbo.AddressBook");
            DropForeignKey("dbo.OrderHistory", "OrderHeader_ID", "dbo.OrderHeader");
            DropForeignKey("dbo.OrderLine", "OrderHeader_ID", "dbo.OrderHeader");
            DropForeignKey("dbo.XREF_TaxCustomer", "OrderHeader_ID", "dbo.OrderHeader");
            DropForeignKey("dbo.OrderLine", "Discount_ID", "dbo.Discount");
            DropForeignKey("dbo.OrderLine", "SKU_ID", "dbo.SKU_Table");
            DropForeignKey("dbo.SKU_Table", "Property_ID", "dbo.Property");
            DropForeignKey("dbo.XREF_CatalogProduct", "Catalog_ID", "dbo.Catalog");
            DropForeignKey("dbo.Catalog", "Vendor_ID", "dbo.Vendor");
            DropForeignKey("dbo.Fullfilment", "Vendor_ID", "dbo.Vendor");
            DropForeignKey("dbo.OrderHeader", "ShippingMethod_ID", "dbo.ShippingMethod");
            DropForeignKey("dbo.OrderHeader", "Status_ID", "dbo.Status");
            DropForeignKey("dbo.XREF_TaxCustomer", "Tax_ID", "dbo.Tax");
            DropForeignKey("dbo.XREF_CustomerRole", "Role_ID", "dbo.Role");
            DropPrimaryKey("dbo.AddressBook");
            DropPrimaryKey("dbo.XREF_AddressBookCustomer");
            DropPrimaryKey("dbo.OrderHistory");
            DropPrimaryKey("dbo.OrderHeader");
            DropPrimaryKey("dbo.OrderLine");
            DropPrimaryKey("dbo.Discount");
            DropPrimaryKey("dbo.SKU_Table");
            DropPrimaryKey("dbo.Property");
            DropPrimaryKey("dbo.XREF_CatalogProduct");
            DropPrimaryKey("dbo.Catalog");
            DropPrimaryKey("dbo.Vendor");
            DropPrimaryKey("dbo.Fullfilment");
            DropPrimaryKey("dbo.ShippingMethod");
            DropPrimaryKey("dbo.Status");
            DropPrimaryKey("dbo.XREF_TaxCustomer");
            DropPrimaryKey("dbo.Tax");
            DropPrimaryKey("dbo.XREF_CustomerRole");
            DropPrimaryKey("dbo.Role");
            DropPrimaryKey("dbo.State");
            AlterColumn("dbo.AddressBook", "AddressBook_ID", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.XREF_AddressBookCustomer", "XREF_AddressBookCustomer_ID", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.OrderHistory", "OrderHistory_ID", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.OrderHeader", "OrderHeader_ID", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.OrderLine", "OrderLine_ID", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Discount", "Discount_ID", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.SKU_Table", "SKU_ID", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Property", "Property_ID", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.XREF_CatalogProduct", "XREF_CatalogProduct_ID", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Catalog", "Catalog_ID", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Vendor", "Vendor_ID", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Fullfilment", "Fullfilment_ID", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.ShippingMethod", "ShippingMethod_ID", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Status", "Status_ID", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.XREF_TaxCustomer", "XREF_TaxCustomer_ID", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Tax", "Tax_ID", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.XREF_CustomerRole", "XREF_CustomerRole_ID", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Role", "Role_ID", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.State", "State_ID", c => c.Int(nullable: false, identity: true));
            AddPrimaryKey("dbo.AddressBook", "AddressBook_ID");
            AddPrimaryKey("dbo.XREF_AddressBookCustomer", "XREF_AddressBookCustomer_ID");
            AddPrimaryKey("dbo.OrderHistory", "OrderHistory_ID");
            AddPrimaryKey("dbo.OrderHeader", "OrderHeader_ID");
            AddPrimaryKey("dbo.OrderLine", "OrderLine_ID");
            AddPrimaryKey("dbo.Discount", "Discount_ID");
            AddPrimaryKey("dbo.SKU_Table", "SKU_ID");
            AddPrimaryKey("dbo.Property", "Property_ID");
            AddPrimaryKey("dbo.XREF_CatalogProduct", "XREF_CatalogProduct_ID");
            AddPrimaryKey("dbo.Catalog", "Catalog_ID");
            AddPrimaryKey("dbo.Vendor", "Vendor_ID");
            AddPrimaryKey("dbo.Fullfilment", "Fullfilment_ID");
            AddPrimaryKey("dbo.ShippingMethod", "ShippingMethod_ID");
            AddPrimaryKey("dbo.Status", "Status_ID");
            AddPrimaryKey("dbo.XREF_TaxCustomer", "XREF_TaxCustomer_ID");
            AddPrimaryKey("dbo.Tax", "Tax_ID");
            AddPrimaryKey("dbo.XREF_CustomerRole", "XREF_CustomerRole_ID");
            AddPrimaryKey("dbo.Role", "Role_ID");
            AddPrimaryKey("dbo.State", "State_ID");
            AddForeignKey("dbo.XREF_AddressBookCustomer", "AddresBook_ID", "dbo.AddressBook", "AddressBook_ID");
            AddForeignKey("dbo.OrderHistory", "OrderHeader_ID", "dbo.OrderHeader", "OrderHeader_ID");
            AddForeignKey("dbo.OrderLine", "OrderHeader_ID", "dbo.OrderHeader", "OrderHeader_ID");
            AddForeignKey("dbo.XREF_TaxCustomer", "OrderHeader_ID", "dbo.OrderHeader", "OrderHeader_ID");
            AddForeignKey("dbo.OrderLine", "Discount_ID", "dbo.Discount", "Discount_ID");
            AddForeignKey("dbo.OrderLine", "SKU_ID", "dbo.SKU_Table", "SKU_ID");
            AddForeignKey("dbo.SKU_Table", "Property_ID", "dbo.Property", "Property_ID");
            AddForeignKey("dbo.XREF_CatalogProduct", "Catalog_ID", "dbo.Catalog", "Catalog_ID");
            AddForeignKey("dbo.Catalog", "Vendor_ID", "dbo.Vendor", "Vendor_ID");
            AddForeignKey("dbo.Fullfilment", "Vendor_ID", "dbo.Vendor", "Vendor_ID");
            AddForeignKey("dbo.OrderHeader", "ShippingMethod_ID", "dbo.ShippingMethod", "ShippingMethod_ID");
            AddForeignKey("dbo.OrderHeader", "Status_ID", "dbo.Status", "Status_ID");
            AddForeignKey("dbo.XREF_TaxCustomer", "Tax_ID", "dbo.Tax", "Tax_ID");
            AddForeignKey("dbo.XREF_CustomerRole", "Role_ID", "dbo.Role", "Role_ID");
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.XREF_CustomerRole", "Role_ID", "dbo.Role");
            DropForeignKey("dbo.XREF_TaxCustomer", "Tax_ID", "dbo.Tax");
            DropForeignKey("dbo.OrderHeader", "Status_ID", "dbo.Status");
            DropForeignKey("dbo.OrderHeader", "ShippingMethod_ID", "dbo.ShippingMethod");
            DropForeignKey("dbo.Fullfilment", "Vendor_ID", "dbo.Vendor");
            DropForeignKey("dbo.Catalog", "Vendor_ID", "dbo.Vendor");
            DropForeignKey("dbo.XREF_CatalogProduct", "Catalog_ID", "dbo.Catalog");
            DropForeignKey("dbo.SKU_Table", "Property_ID", "dbo.Property");
            DropForeignKey("dbo.OrderLine", "SKU_ID", "dbo.SKU_Table");
            DropForeignKey("dbo.OrderLine", "Discount_ID", "dbo.Discount");
            DropForeignKey("dbo.XREF_TaxCustomer", "OrderHeader_ID", "dbo.OrderHeader");
            DropForeignKey("dbo.OrderLine", "OrderHeader_ID", "dbo.OrderHeader");
            DropForeignKey("dbo.OrderHistory", "OrderHeader_ID", "dbo.OrderHeader");
            DropForeignKey("dbo.XREF_AddressBookCustomer", "AddresBook_ID", "dbo.AddressBook");
            DropPrimaryKey("dbo.State");
            DropPrimaryKey("dbo.Role");
            DropPrimaryKey("dbo.XREF_CustomerRole");
            DropPrimaryKey("dbo.Tax");
            DropPrimaryKey("dbo.XREF_TaxCustomer");
            DropPrimaryKey("dbo.Status");
            DropPrimaryKey("dbo.ShippingMethod");
            DropPrimaryKey("dbo.Fullfilment");
            DropPrimaryKey("dbo.Vendor");
            DropPrimaryKey("dbo.Catalog");
            DropPrimaryKey("dbo.XREF_CatalogProduct");
            DropPrimaryKey("dbo.Property");
            DropPrimaryKey("dbo.SKU_Table");
            DropPrimaryKey("dbo.Discount");
            DropPrimaryKey("dbo.OrderLine");
            DropPrimaryKey("dbo.OrderHeader");
            DropPrimaryKey("dbo.OrderHistory");
            DropPrimaryKey("dbo.XREF_AddressBookCustomer");
            DropPrimaryKey("dbo.AddressBook");
            AlterColumn("dbo.State", "State_ID", c => c.Int(nullable: false));
            AlterColumn("dbo.Role", "Role_ID", c => c.Int(nullable: false));
            AlterColumn("dbo.XREF_CustomerRole", "XREF_CustomerRole_ID", c => c.Int(nullable: false));
            AlterColumn("dbo.Tax", "Tax_ID", c => c.Int(nullable: false));
            AlterColumn("dbo.XREF_TaxCustomer", "XREF_TaxCustomer_ID", c => c.Int(nullable: false));
            AlterColumn("dbo.Status", "Status_ID", c => c.Int(nullable: false));
            AlterColumn("dbo.ShippingMethod", "ShippingMethod_ID", c => c.Int(nullable: false));
            AlterColumn("dbo.Fullfilment", "Fullfilment_ID", c => c.Int(nullable: false));
            AlterColumn("dbo.Vendor", "Vendor_ID", c => c.Int(nullable: false));
            AlterColumn("dbo.Catalog", "Catalog_ID", c => c.Int(nullable: false));
            AlterColumn("dbo.XREF_CatalogProduct", "XREF_CatalogProduct_ID", c => c.Int(nullable: false));
            AlterColumn("dbo.Property", "Property_ID", c => c.Int(nullable: false));
            AlterColumn("dbo.SKU_Table", "SKU_ID", c => c.Int(nullable: false));
            AlterColumn("dbo.Discount", "Discount_ID", c => c.Int(nullable: false));
            AlterColumn("dbo.OrderLine", "OrderLine_ID", c => c.Int(nullable: false));
            AlterColumn("dbo.OrderHeader", "OrderHeader_ID", c => c.Int(nullable: false));
            AlterColumn("dbo.OrderHistory", "OrderHistory_ID", c => c.Int(nullable: false));
            AlterColumn("dbo.XREF_AddressBookCustomer", "XREF_AddressBookCustomer_ID", c => c.Int(nullable: false));
            AlterColumn("dbo.AddressBook", "AddressBook_ID", c => c.Int(nullable: false));
            AddPrimaryKey("dbo.State", "State_ID");
            AddPrimaryKey("dbo.Role", "Role_ID");
            AddPrimaryKey("dbo.XREF_CustomerRole", "XREF_CustomerRole_ID");
            AddPrimaryKey("dbo.Tax", "Tax_ID");
            AddPrimaryKey("dbo.XREF_TaxCustomer", "XREF_TaxCustomer_ID");
            AddPrimaryKey("dbo.Status", "Status_ID");
            AddPrimaryKey("dbo.ShippingMethod", "ShippingMethod_ID");
            AddPrimaryKey("dbo.Fullfilment", "Fullfilment_ID");
            AddPrimaryKey("dbo.Vendor", "Vendor_ID");
            AddPrimaryKey("dbo.Catalog", "Catalog_ID");
            AddPrimaryKey("dbo.XREF_CatalogProduct", "XREF_CatalogProduct_ID");
            AddPrimaryKey("dbo.Property", "Property_ID");
            AddPrimaryKey("dbo.SKU_Table", "SKU_ID");
            AddPrimaryKey("dbo.Discount", "Discount_ID");
            AddPrimaryKey("dbo.OrderLine", "OrderLine_ID");
            AddPrimaryKey("dbo.OrderHeader", "OrderHeader_ID");
            AddPrimaryKey("dbo.OrderHistory", "OrderHistory_ID");
            AddPrimaryKey("dbo.XREF_AddressBookCustomer", "XREF_AddressBookCustomer_ID");
            AddPrimaryKey("dbo.AddressBook", "AddressBook_ID");
            AddForeignKey("dbo.XREF_CustomerRole", "Role_ID", "dbo.Role", "Role_ID");
            AddForeignKey("dbo.XREF_TaxCustomer", "Tax_ID", "dbo.Tax", "Tax_ID");
            AddForeignKey("dbo.OrderHeader", "Status_ID", "dbo.Status", "Status_ID");
            AddForeignKey("dbo.OrderHeader", "ShippingMethod_ID", "dbo.ShippingMethod", "ShippingMethod_ID");
            AddForeignKey("dbo.Fullfilment", "Vendor_ID", "dbo.Vendor", "Vendor_ID");
            AddForeignKey("dbo.Catalog", "Vendor_ID", "dbo.Vendor", "Vendor_ID");
            AddForeignKey("dbo.XREF_CatalogProduct", "Catalog_ID", "dbo.Catalog", "Catalog_ID");
            AddForeignKey("dbo.SKU_Table", "Property_ID", "dbo.Property", "Property_ID");
            AddForeignKey("dbo.OrderLine", "SKU_ID", "dbo.SKU_Table", "SKU_ID");
            AddForeignKey("dbo.OrderLine", "Discount_ID", "dbo.Discount", "Discount_ID");
            AddForeignKey("dbo.XREF_TaxCustomer", "OrderHeader_ID", "dbo.OrderHeader", "OrderHeader_ID");
            AddForeignKey("dbo.OrderLine", "OrderHeader_ID", "dbo.OrderHeader", "OrderHeader_ID");
            AddForeignKey("dbo.OrderHistory", "OrderHeader_ID", "dbo.OrderHeader", "OrderHeader_ID");
            AddForeignKey("dbo.XREF_AddressBookCustomer", "AddresBook_ID", "dbo.AddressBook", "AddressBook_ID");
        }
    }
}
